name: Continuous integration 

on:
 pull_request:
   branches:
     -main
jobs:
  test:
    name: 'Run unit tests'
    defaults:
      run:
        shell: bash
        # Define the working directory for all run steps in the workflow
        working-directory: ./app
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
      name: 'checkout-repo'

    - name: 'install dependancy'
      run: npm  install

    - name: 'testing-code'
      run: npm run test
